language: ruby
sudo: false
before_install:
  - gem install bundler
  - "rm -f ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
  - mysql -e 'create database archiving_test'
  - cd test/dummy
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../..
cache: bundler
rvm:
  - 2.0
  - 2.1.6
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/active_record-3.2.gemfile
  - gemfiles/active_record-4.0.gemfile
  - gemfiles/active_record-4.1.gemfile
  - gemfiles/active_record-4.2.gemfile

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.2.5
      gemfile: gemfiles/active_record-3.2.gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/active_record-3.2.gemfile

notifications:
  email: false