language: ruby
sudo: false
before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.0
  - 2.1

env:
  - "RAILS_VERSION=3.2.19"

matrix:
  allow_failures:
    - rvm: 2.2

notifications:
  email: false